apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-api-pvc"
  namespace: "{{ .Release.Namespace }}"
  labels:
{{- include "api.labels" . | nindent 4 }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "{{ .Values.api.storage.class }}"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.api.storage.size }}"