name: Deploy
on: 
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'treasury_release'
        namespace: 'kkushal'
        chart: 'app'
        token: '${{ github.token }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
