name: Deploy
on: ['deployment']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'treasury_release'
        namespace: 'default'
        chart: './charts/helm'
        token: '${{ github.token }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
