name: Deploy
on: 
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'treasuryrelease'
        namespace: 'kkushal'
        chart: './charts/treasury'
        token: '${{ github.token }}'
        helm: 'helm3'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
